//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ProcessAppMobile.Droid.WS_Process {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceProcessSoap", Namespace="http://tempuri.org/")]
    public partial class ServiceProcess : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback DashBoardOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceProcess() {
            this.Url = "http://localhost/LocalWs/ServiceProcess.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event DashBoardCompletedEventHandler DashBoardCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Login(string usu, string pass) {
            object[] results = this.Invoke("Login", new object[] {
                        usu,
                        pass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string usu, string pass) {
            this.LoginAsync(usu, pass, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string usu, string pass, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        usu,
                        pass}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DashBoard", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DashboardGen[] DashBoard(int rut, string rut_empresa) {
            object[] results = this.Invoke("DashBoard", new object[] {
                        rut,
                        rut_empresa});
            return ((DashboardGen[])(results[0]));
        }
        
        /// <remarks/>
        public void DashBoardAsync(int rut, string rut_empresa) {
            this.DashBoardAsync(rut, rut_empresa, null);
        }
        
        /// <remarks/>
        public void DashBoardAsync(int rut, string rut_empresa, object userState) {
            if ((this.DashBoardOperationCompleted == null)) {
                this.DashBoardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDashBoardOperationCompleted);
            }
            this.InvokeAsync("DashBoard", new object[] {
                        rut,
                        rut_empresa}, this.DashBoardOperationCompleted, userState);
        }
        
        private void OnDashBoardOperationCompleted(object arg) {
            if ((this.DashBoardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DashBoardCompleted(this, new DashBoardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DashboardGen {
        
        private string nOMBRE_UNIDADField;
        
        private int iD_TAREAField;
        
        private string nOMBRE_TAREAField;
        
        private string fECHA_TERMINOField;
        
        private System.DateTime fECHACREACIONField;
        
        private string fECHA_ACTUALField;
        
        private string fECHA_ESTIMADAField;
        
        private string eSTADOField;
        
        private int rut_UsuField;
        
        private int tareas_terField;
        
        private int cant_tareas_totField;
        
        private int procentajeField;
        
        private string nombre_usurioField;
        
        private int aTRASOField;
        
        private DashboardGen[] listgenField;
        
        /// <remarks/>
        public string NOMBRE_UNIDAD {
            get {
                return this.nOMBRE_UNIDADField;
            }
            set {
                this.nOMBRE_UNIDADField = value;
            }
        }
        
        /// <remarks/>
        public int ID_TAREA {
            get {
                return this.iD_TAREAField;
            }
            set {
                this.iD_TAREAField = value;
            }
        }
        
        /// <remarks/>
        public string NOMBRE_TAREA {
            get {
                return this.nOMBRE_TAREAField;
            }
            set {
                this.nOMBRE_TAREAField = value;
            }
        }
        
        /// <remarks/>
        public string FECHA_TERMINO {
            get {
                return this.fECHA_TERMINOField;
            }
            set {
                this.fECHA_TERMINOField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FECHACREACION {
            get {
                return this.fECHACREACIONField;
            }
            set {
                this.fECHACREACIONField = value;
            }
        }
        
        /// <remarks/>
        public string FECHA_ACTUAL {
            get {
                return this.fECHA_ACTUALField;
            }
            set {
                this.fECHA_ACTUALField = value;
            }
        }
        
        /// <remarks/>
        public string FECHA_ESTIMADA {
            get {
                return this.fECHA_ESTIMADAField;
            }
            set {
                this.fECHA_ESTIMADAField = value;
            }
        }
        
        /// <remarks/>
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
            }
        }
        
        /// <remarks/>
        public int Rut_Usu {
            get {
                return this.rut_UsuField;
            }
            set {
                this.rut_UsuField = value;
            }
        }
        
        /// <remarks/>
        public int Tareas_ter {
            get {
                return this.tareas_terField;
            }
            set {
                this.tareas_terField = value;
            }
        }
        
        /// <remarks/>
        public int Cant_tareas_tot {
            get {
                return this.cant_tareas_totField;
            }
            set {
                this.cant_tareas_totField = value;
            }
        }
        
        /// <remarks/>
        public int procentaje {
            get {
                return this.procentajeField;
            }
            set {
                this.procentajeField = value;
            }
        }
        
        /// <remarks/>
        public string nombre_usurio {
            get {
                return this.nombre_usurioField;
            }
            set {
                this.nombre_usurioField = value;
            }
        }
        
        /// <remarks/>
        public int ATRASO {
            get {
                return this.aTRASOField;
            }
            set {
                this.aTRASOField = value;
            }
        }
        
        /// <remarks/>
        public DashboardGen[] listgen {
            get {
                return this.listgenField;
            }
            set {
                this.listgenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DashBoardCompletedEventHandler(object sender, DashBoardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DashBoardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DashBoardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DashboardGen[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DashboardGen[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591